### ISSUE TITLE
Request for sound config toggle

### ISSUE THREAD

**Issue by masonmanley** [leothawne/LTSleepNStorm#1]
**Is your feature request related to a problem? Please describe.**
Config option to disable sound effect

**Describe the solution you'd like**
Config option to disable sound effect

**Comment by leothawne** [comment]
Thank you for your suggestion!

Just to make it clear: an option to disable the sound will also disable the lightning strike too. I'm not sure if I can prevent this from happening.

**Comment by masonmanley** [comment]
Yeh that is what I am looking for! Thanks

**Comment by leothawne** [comment]
New config added: https://github.com/leothawne/LTSleepNStorm/commit/36a93c926577abf60202badfd54b965aef488cc5
New version available at: https://github.com/leothawne/LTSleepNStorm/releases/tag/0.2.2
