### ISSUE TITLE
Invalid message on join

### ISSUE THREAD

**Issue by masonmanley** [leothawne/LTSleepNStorm#2]
**Describe the bug**
When joining server with full permissions, message saying: "[LTSNS :: Admin] Invalid command! Type /sleepnstormadmin to see all available commands" is shown

**To Reproduce**
1. Give full perms to user
2. Join server as user
3. Check chat

**Expected behavior**
This message shouldn't be thing and shouldn't appear

**Screenshots**
http://prntscr.com/o0ufk5

**Comment by leothawne** [comment]
Issue fixed: https://github.com/leothawne/LTSleepNStorm/commit/36a93c926577abf60202badfd54b965aef488cc5
New version available at: https://github.com/leothawne/LTSleepNStorm/releases/tag/0.2.2
